image: docker:latest

variables:
  REPOSITORY_URL:

services:
- docker:dind

stages:
  - build
  - deploy

build_prod:
  stage: build
  script:
    - npm install
    - NODE_ENV=production npm run build
    -  $(aws ecr get-login --no-include-email --region us-east-1)
    - docker build -t $REPOSITORY_URL:$CI_BUILD_REF -f DockerfileProd .
    - docker push $REPOSITORY_URL
  only:
    - master
  tags:
    - docker


build_dev:
  stage: build
  script:
    - npm install
    - npm run builddev
    -  $(aws ecr get-login --no-include-email --region us-east-1)
    - docker build -t $REPOSITORY_URL:$CI_BUILD_REF -f DockerfileDev .
    - docker push $REPOSITORY_URL
  only:
    - development
  tags:
    - docker


deploy_prod:
  stage: deploy
  script:
      only:
    - master
  tags:
    - docker

deploy_dev:
  stage: deploy
  script:
     only:
    - development
  tags:
    - docker
